[package]
name = "ggez_snake"
version = "0.2.0"
authors = ["Maurizio Crocci <mbcrocci@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "*"
rand = "*"